repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.4.8'
    hooks:
      - id: ruff
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [--strip-extras, --output-file=requirements.txt]
        files: ^(pyproject\.toml|requirements\.txt)$
      - id: pip-compile
        name: pip-compile requirements-test.txt
        args: [--extra=test, --strip-extras, --output-file=requirements-test.txt]
        files: ^(pyproject\.toml|requirements-test\.txt)$
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args: [--extra=dev, --strip-extras, --output-file=requirements-dev.txt]
        files: ^(pyproject\.toml|requirements-dev\.txt)$
      - id: pip-compile
        name: pip-compile requirements-flask.txt
        args: [--extra=flask, --strip-extras, --output-file=requirements-flask.txt]
        files: ^(pyproject\.toml|requirements-flask\.txt)$
      - id: pip-compile
        name: pip-compile requirements-starlette.txt
        args: [--extra=starlette, --strip-extras, --output-file=requirements-starlette.txt]
        files: ^(pyproject\.toml|requirements-starlette\.txt)$
      - id: pip-compile
        name: pip-compile requirements-kafka.txt
        args: [--extra=kafka, --strip-extras, --output-file=requirements-kafka.txt]
        files: ^(pyproject\.toml|requirements-kafka\.txt)$
