[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "FVH-IoT"
description = "Utilities for FVH's IoT projects"
version = "0.3.0"
authors = [
    { name = "Aapo Rista", email = "aapo.rista@forumvirium.fi" }
]
dependencies = [
    'Flask',
    'starlette',
    'certifi',
    'kafka-python',
    'msgpack',
]
